### PR TITLE
made it possible to vote with trezor and updated the voting library version

### PR DESCRIPTION
**Pull request by shierve**
I used my new library nem-trezor to integrate trezor and voting. Now you can create and vote on polls with trezor.

### CODE REVIEW

**Comment by QuantumMechanics** [comment]
Hi,

Poll creation doesn't work without trezor, I get:

>Error: t is not defined

**Comment by shierve** [comment]
Ok I will fix it today

**Comment by shierve** [comment]
Should be fixed. I tested without Trezor and it works now, it was a stupid mistake sorry.

**Comment by QuantumMechanics** [comment]
All good now, thanks

**Pull request merged**
