### PR TITLE
Create file ko.js

### PR DESCRIPTION
**Pull request by EvertonMelo**
add support Korean

### CODE REVIEW

**Comment by EvertonMelo** [comment]
#545

**Comment by EvertonMelo** [comment]
#546

**Comment by EvertonMelo** [comment]
@cryptoBeliever 

Thank your for your fast feedback, 

I am at your disposal

**Comment by cryptoBeliever** [comment]
Please confirm that your native language is Korean (as I can see you have Brasil in profile).

**Comment by EvertonMelo** [comment]
@cryptoBeliever 

Do you have any position on what you are going to do with this PR?

**Comment by cryptoBeliever** [comment]
Hello @EvertonMelo 
Today I asked one member from the Korean community to review your translation.

**Comment by EvertonMelo** [comment]
@cryptoBeliever 

would not it be interesting to first accept the PR and then review? 

notice the project history.
see for example translations into Japanese. 
 
#542
#530 
#509 
#461 

Why did not you act that way?

**Comment by cryptoBeliever** [comment]
When PR will be merged review makes no sense because it will be already in the main branch and will be included in next wallet release so dev has no control on it if it will be reviewed as bad (need to revert and so on). Japanese original translation with you referring was first reviewed by @mizunashi and next merged (#461). After that was some new pull requests but only with additional messages made by the same author.

Because I'm not sure if your native language is Korean (all previous translations were done by native speakers from the community and in my opinion only such should be accepted) I asked Korean community member to make the review. If it will be not clear for him we can't accept it. Wrong translation in the wallet can lead to mistake and loss of XEM (or other tokens). I hope you understand this.

Thank you.

**Pull request closed without merging**
