### PR TITLE
Fixed issue with version incompatibilities

### PR DESCRIPTION
**Pull request by shierve**
there was an important issue that made voting on old versions cause wrong results. The poll structure has been changed so that this will not happen on future versions. People should make sure to have an actual version for voting.

### CODE REVIEW

**Comment by mizunashi** [comment]
@QuantumMechanics 
The new Voting module is incompatible with the current one.
NanoWallet needs to be **mandatory update**.

**Comment by QuantumMechanics** [comment]
Hi,

Please can you remove package-lock.json

**Comment by shierve** [comment]
I have removed package-lock and added addresses to the exchange blacklist

**Comment by shierve** [comment]
I have made the requested changes

**Pull request merged**
