### PR TITLE
Neutral Spanish translation revised in detail

### PR DESCRIPTION
**Pull request by noriammx**
A detailed review of the translation of each of the modules was carried out in conjunction with @nmarmon and @jonabasque. This translation is intended to be a neutral translation so that it can be understood by any Spanish speaker.

### CODE REVIEW

**Comment by noriammx** [comment]
Address for bounties: NDOV64-7HRZ46-MX2SUB-WVPXAO-IJC4IP-XHMD5P-DUBB

**Comment by jonabasque** [comment]
We have worked a lot on this translation, I think it is ready to be used.

The merge would be fantastic.

**Comment by cryptoBeliever** [comment]
@QuantumMechanics could we count this translation will be merged soon?

**Comment by fyahfox** [comment]
Bounty paid. Tx hash: f445a459b43d962b864888b6206904c6b720716bc87a9427861b23fe987b3731

**Pull request merged**
