### PR TITLE
Apply Chrome specific privacy settings when running under nw.js

### PR DESCRIPTION
**Pull request by akkie**
Chrome has enabled some privacy settings per default, which may affect the security of the NanoWallet when running the standalone client under nw.js. This pull request disables multiple settings which are not needed by the standalone client. The `passwordSavingEnabled` setting which is enabled by the default may also cause security issues because it stores automatically the passwords entered into the wallet.

The following settings will be disabled:
- chrome.privacy.services.alternateErrorPagesEnabled
- chrome.privacy.services.autofillEnabled
- chrome.privacy.services.hotwordSearchEnabled
- chrome.privacy.services.passwordSavingEnabled
- chrome.privacy.services.safeBrowsingExtendedReportingEnabled
- chrome.privacy.services.searchSuggestEnabled
- chrome.privacy.services.spellingServiceEnabled
- chrome.privacy.services.translationServiceEnabled

A complete list of the privacy settings can be found on this page: https://developer.chrome.com/extensions/privacy

This refers also to https://github.com/nwjs/nw.js/issues/5944

The pull request updates also nw.js to 0.25.4 and it orders the dependencies in the package.json file.

Bounty address: NCZ7JL-IG2PVY-JGN7IN-HS65TB-SW66AT-4INETE-TUGJ

### CODE REVIEW

**Comment by QuantumMechanics** [comment]
Thanks

**Comment by QuantumMechanics** [comment]
`src/app/config/nw.js` line 21 `chrome` is not defined

**Comment by akkie** [comment]
OK, will provide a fix

**Comment by QuantumMechanics** [comment]
Going to push a fix

```javascript
// Apply nw.js config if using Chrome
if (/Chrome/.test(navigator.userAgent) && /Google Inc/.test(navigator.vendor)) {
    nwConfig();
}
```

**Comment by akkie** [comment]
@QuantumMechanics 

In my opinion it would be better to test against the window object:
```js
const applyChromeSetting = (prop, value) => {
    const settingsObject = get(window, prop);
```

And use the full property: 
```js
applyChromeSetting('chrome.privacy.services.alternateErrorPagesEnabled', false);
```

This works as expected in other browsers. Means that it logs the messages:
```
Setting `chrome.privacy.services.alternateErrorPagesEnabled` cannot be handled by this browser. This is the expected behavior if you don't run the standalone NanoWallet!
```

**Comment by jabo38** [comment]
Bounty paid. Tx hash: d3e898597cf612b807521507587eab9351b00974afe207004001609fd7f671b0

**Comment by HC1988** [comment]
@akkie “chrome.privacy.services.passwordSavingEnabled” it works well and so nice for nwjs.

**Pull request merged**
