### PR TITLE
add it.js support to italian 

### PR DESCRIPTION
**Pull request by EvertonMelo**
Translation to italian.
address Bounty: NDI55N-OEHLZS-PNIZEU-L2XU7S-3477UZ-PBNZ5Q-5BPQ

### CODE REVIEW

**Comment by EvertonMelo** [comment]
#518 part to support

**Comment by EvertonMelo** [comment]
#519 part2 to on support

**Comment by QuantumMechanics** [comment]
Hi,

Please can you group your pull requests into one, also the `it.js` file must not have a `+` at the beginning of every line. Thanks :)

**Comment by EvertonMelo** [comment]
@QuantumMechanics 

Thank you for Accept my PR.

if you could help me. let the Foundation know about my contribution and my "Bounty"


 
--

**Comment by nemster** [comment]
@EvertonMelo your italian isn't very good.
Did you use Google Translate for the text?
I asked another guy to review it.

**Comment by EvertonMelo** [comment]
@QuantumMechanics 

thank you

**Comment by fyahfox** [comment]
bounty paid
TX hash: 95fcb1243c1e9d204eab0443c0690157d17223aad0d00b807267ef809a5d268c

**Comment by EvertonMelo** [comment]
@fyahfox 

thank you, it was an honor for me

**Pull request merged**
